### ISSUE TITLE
Great work

### ISSUE THREAD

**Issue by Forceflow** [kevinhartman/morton-nd#1]
Couldn't find a contact e-mail,  so slightly abusing this issue tracker to drop a line that I like the work you did integrating your project with libmorton.

If there are any fixes you'd like me to incorporate, don't hesitate to let me know.

**Comment by kevinhartman** [comment]
Hi @Forceflow,

Thanks for the note and for your work on Morton encoding.

I came across a bug in the 2D 'For' and 'For ET' implementations in libmorton for which I'll submit a PR. I was hoping to clean up and include the 2D validation code I'd added in my fork as well. Stay tuned.

More generally speaking, my original thought was to contribute the contents of this project to libmorton itself, but I elected for a separate project since Morton ND's code has a hard dependency on C++14, and it's easier for me to maintain this code as a project owner on GH. I will be sure to PR any generally useful C++11 compatible enhancements I make to my libmorton fork 😎.

Feel free to reach me at kevin@hart.mn for any suggestions etc.
